const Numbers = [
  [
    0,
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/0.png',
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/0-2.png',
  ],
  [
    1,
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/1.png',
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/1-2.png',
  ],
  [
    2,
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/2.png',
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/2-2.png',
  ],
  [
    3,
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/3.png',
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/3-2.png',
  ],
  [
    4,
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/4.png',
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/4-2.png',
  ],
  [
    5,
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/5.png',
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/5-2.png',
  ],
  [
    6,
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/6.png',
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/6-2.png',
  ],
  [
    7,
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/7.png',
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/7-2.png',
  ],
  [
    8,
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/8.png',
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/8-2.png',
  ],
  [
    9,
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/9.png',
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/9-2.png',
  ],
  [
    10,
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/10.png',
    'https://s3-us-west-1.amazonaws.com/otsimo-en/numbers/10-2.png',
  ],
];
export default Numbers;
